namespace JewelryManager.Api.Features.Invoices;

/// <summary>Invoice files on the disk of the server, one folder per business, outside the web root.</summary>
public class LocalInvoiceStorage(string rootPath) : IInvoiceStorage
{
    public async Task SaveAsync(Guid businessId, string storedName, Stream content)
    {
        var path = PathFor(businessId, storedName);
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);

        await using var file = File.Create(path);
        await content.CopyToAsync(file);
    }

    public Task<Stream?> OpenReadAsync(Guid businessId, string storedName)
    {
        var path = PathFor(businessId, storedName);
        return Task.FromResult<Stream?>(File.Exists(path) ? File.OpenRead(path) : null);
    }

    public Task DeleteAsync(Guid businessId, string storedName)
    {
        File.Delete(PathFor(businessId, storedName));
        return Task.CompletedTask;
    }

    // Stored names are generated by the server (a GUID and a fixed extension), but the check
    // keeps a bad value from ever reaching outside the business folder.
    private string PathFor(Guid businessId, string storedName)
    {
        if (storedName != Path.GetFileName(storedName))
            throw new ArgumentException("Invalid stored file name", nameof(storedName));

        return Path.Combine(rootPath, businessId.ToString("N"), storedName);
    }
}
